apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
  namespace: istio-system
spec:
  tracing:
    type: None
  addons:
    grafana:
      enabled: false
    kiali:
      name: kiali
      enabled: false
    prometheus:
      enabled: false
    jaeger: 
      name: jaeger
  security:
    dataPlane:
      mtls: true # otherwise inference-graph will not work. We use PeerAuthentication resources to force mTLS
    identity:
      type: ThirdParty        
  techPreview:
    meshConfig:
      defaultConfig:
        terminationDrainDuration: 35s
  gateways:
    ingress:
      service:
        metadata:
          labels:
            knative: ingressgateway
      runtime:
        container:
          resources:
            limits:
              memory: 4Gi
    egress:
      runtime:
        container:
          resources:
            limits:
              memory: 4Gi
  proxy:
    networking:
      trafficControl:
        inbound:
          excludedPorts:
            - 8444 # metrics
            - 8022 # serving: wait-for-drain k8s pre-stop hook              
  profiles:
    - default
