apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-tgis-runtime
spec:
  multiModel: false
  supportedModelFormats:
    # Note: this currently *only* supports caikit format models
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      command: ["text-generation-launcher"]
      args: ["--model-name=/mnt/models/artifacts/"]
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      resources: # configure as required
        requests:
          cpu: 16
          memory: 32Gi
    - name: transformer-container
      image: quay.io/opendatahub/caikit-tgis-serving:stable
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
      ports:
        - containerPort: 8085
          # 8080 for http, 8085 for grpc?
          # https://github.com/opendatahub-io/caikit-tgis-serving/pull/131
          name: h2c
          protocol: TCP
      resources: # configure as required
        requests:
          cpu: 16
          memory: 32Gi
    - name: helper
      image: quay.io/wangzheng422/debug-pod:alma-9.3
      securityContext:
        # privileged: true
        AllowPrivilegedContainer: true
      env:
        - name: key
          value: value
      command: 
        - sleep
        - infinity